
# Order
POST http://127.0.0.1:7071/api/order HTTP/1.1
content-type: application/json

{
  "name": "Craig Shoemaker",
  "email": "craig@example.com",
  "phone": "+15555555555", 
  "productId": 1001,
  "key": "hardware",
  "quantity": 10
}
